.TH POMODORO-TIMER 6 2019-03-21
.SH NAME
Pomodoro timer \- the simple pomodoro timer implemented in Qt
.SH SYNOPSIS
.B pomodoro-timer
.SH DESCRIPTION
Set  timer to 20 min work 5 min rest.
.SH OPTIONS
Pomodoro-timer is configured graphically and does not have any commandline options.
.SH FILES
~/.config/pomodoro-timer/pomodoro-timer.conf
.RS
Per user configuration file.
.RE
.SH BUGS
If you find a bug, please notify the author.
.SH AUTHOR
ZanyXDev <zanyxev@gmail.com>
